# Generated by Django 4.2.13 on 2024-07-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_excelfile_file_alter_pptfile_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excelfile",
            name="file",
            field=models.FileField(upload_to="excel_files/"),
        ),
        migrations.AlterField(
            model_name="pptfile",
            name="file",
            field=models.FileField(upload_to="ppt_files/"),
        ),
        migrations.AlterField(
            model_name="pythonproject",
            name="file",
            field=models.FileField(upload_to="python_files/"),
        ),
    ]
